version: "3"

services:
  squid-npm:
    image: mountainpass/squid-npm
    container_name: squid-npm
    build: .
    ports:
      - "3128:3128"
      - "4128:4128"
    environment:
      - CN=squid.local
      - O=squid
      - OU=squid
      - C=AU
    volumes:
      - ./example:/squid
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
